# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
stages:
      - stage: "Installing_Packer"
        displayName: Packer
        jobs: 
          - job: install
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  source:  specific
                  project: golang-webapp
                  pipeline: 9
                  artifact: WebApp 
              - bash: |
                  ls -lrt
                  pwd 
              - bash: sh packer_setup.sh
      - stage: "Building_image"
        displayName: Build
        jobs: 
          - job: build
            steps:
              - task: "AzureKeyVault@2"
                inputs:
                  connectedServiceName: 'kv_read'
                  KeyVaultName: 'azure-key-pair-new'
                  SecretsFilter: '*'
                  RunAsPreJob: false


                 
               
                      
              