# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
stages:
      - stage: "Installing Packer"
        displayName: Packer
        jobs: 
          - job: install
            steps:
              - bash: sh packer_setup.sh
      - stage: "Building image"
        displayName: Build
        jobs: 
          - job: build
            steps:
              - bash: packer build -var 'az_client_secret=YgF~0Tdf~KFhWOQP6_WPBvI7D6JFnGPmaz' -var 'aws_sub_kid=b791e0a8-9e09-40ba-bbf0-21e6e29d2e67'  ubuntu.json

              