# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
stages:
      - stage: "Installing_Packer"
        displayName: Packer
        jobs: 
          - job: install
            steps:
              - bash: sh packer_setup.sh
      - stage: "Building_image"
        displayName: Build
        jobs: 
          - job: build
            steps:
              - task: "AzureKeyVault@2"
                inputs:
                  azureSubscription: 'b791e0a8-9e09-40ba-bbf0-21e6e29d2e67'
                  KeyVaultName: 'azure-key-pair'
                  SecretsFilter: '*'
                  RunAsPreJob: false
                      
              - bash: packer build -var "az_client_secret=$client-secret" -var "aws_sub_kid=$sub-id"  ubuntu.json

              