# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
pool:
    vmImage: ubuntu-latest
  
stages:
      - stage: "Installing_Packer"
        displayName: Packer
        jobs: 
          - job: install
            steps:
              - bash: |
                  ls -lrt
                  pwd 
              - bash: sh packer_setup.sh
      - stage: "Building_image"
        displayName: Build
        jobs: 
          - job: build
            steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'specific'
                  project: 'ac00ecf6-fd0e-491e-be0c-a5f0b3ba47d9'
                  definition: '9'
                  buildVersionToDownload: 'latest'
                  artifactName: 'WebApp'
                  targetPath: '$(Pipeline.Workspace)'
              - task: "AzureKeyVault@2"
                inputs:
                  connectedServiceName: 'kv_read'
                  KeyVaultName: 'azure-key-pair-new'
                  SecretsFilter: '*'
                  RunAsPreJob: false


                 
               
                      
              